#ifndef PPDT
#	define PPDT 1
#
#	include "ppdt/date/select.h"
#	include "ppdt/time/select.h"
#	include "ppdt/day.h"
#	include "ppdt/leap_year.h"
#	include "ppdt/month.h"
#
#	define PPDT_PCAT(x, ...) x##__VA_ARGS__
#	define PPDT_PSTR(...) #__VA_ARGS__
#	define PPDT_STR(...) PPDT_PSTR(__VA_ARGS__)
#
#	define PPDT_LEAP_YEAR(y) PPDT_PCAT(PPDT_LEAP_YEAR_, y)
#
#	define PPDT_MONTH_NAME(m) PPDT_PCAT(PPDT_MONTH_NAME_, m)
#	define PPDT_MONTH_NAME_UPPER(m) PPDT_PCAT(PPDT_MONTH_NAME_UPPER_, m)
#	define PPDT_MONTH_NAME_LOWER(m) PPDT_PCAT(PPDT_MONTH_NAME_LOWER_, m)
#	define PPDT_MONTH_NAME_SHORT(m) PPDT_PCAT(PPDT_MONTH_NAME_, m)
#	define PPDT_MONTH_NAME_SHORT_UPPER(m) PPDT_PCAT(PPDT_MONTH_NAME_UPPER_, m)
#	define PPDT_MONTH_NAME_SHORT_LOWER(m) PPDT_PCAT(PPDT_MONTH_NAME_LOWER_, m)
#	define PPDT_MONTH_STR(m) PPDT_STR(PPDT_MONTH_NAME(m))
#	define PPDT_MONTH_STR_UPPER(m) PPDT_STR(PPDT_MONTH_NAME_UPPER(m))
#	define PPDT_MONTH_STR_LOWER(m) PPDT_STR(PPDT_MONTH_NAME_LOWER(m))
#	define PPDT_MONTH_STR_SHORT(m) PPDT_STR(PPDT_MONTH_NAME_SHORT(m))
#	define PPDT_MONTH_STR_SHORT_UPPER(m) PPDT_STR(PPDT_MONTH_NAME_SHORT_UPPER(m))
#	define PPDT_MONTH_STR_SHORT_LOWER(m) PPDT_STR(PPDT_MONTH_NAME_SHORT_LOWER(m))
#
#	define PPDT_DAY_NAME(d) PPDT_PCAT(PPDT_DAY_NAME_, d)
#	define PPDT_DAY_NAME_UPPER(d) PPDT_PCAT(PPDT_DAY_NAME_UPPER_, d)
#	define PPDT_DAY_NAME_LOWER(d) PPDT_PCAT(PPDT_DAY_NAME_LOWER_, d)
#	define PPDT_DAY_NAME_SHORT(d) PPDT_PCAT(PPDT_DAY_NAME_SHORT_, d)
#	define PPDT_DAY_NAME_SHORT_UPPER(d) PPDT_PCAT(PPDT_DAY_NAME_SHORT_UPPER_, d)
#	define PPDT_DAY_NAME_SHORT_LOWER(d) PPDT_PCAT(PPDT_DAY_NAME_SHORT_LOWER_, d)
#	define PPDT_DAY_STR(d) PPDT_STR(PPDT_DAY_NAME(d))
#	define PPDT_DAY_STR_UPPER(d) PPDT_STR(PPDT_DAY_NAME_UPPER(d))
#	define PPDT_DAY_STR_LOWER(d) PPDT_STR(PPDT_DAY_NAME_LOWER(d))
#	define PPDT_DAY_STR_SHORT(d) PPDT_STR(PPDT_DAY_NAME_SHORT(d))
#	define PPDT_DAY_STR_SHORT_UPPER(d) PPDT_STR(PPDT_DAY_NAME_SHORT_UPPER(d))
#	define PPDT_DAY_STR_SHORT_LOWER(d) PPDT_STR(PPDT_DAY_NAME_SHORT_LOWER(d))
#endif
